name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  
    - run: npm install    # Instala las dependencias
    - name: Give execute permissions to Mocha
      run: chmod +x ./node_modules/.bin/mocha
    - run: npm test       # Ejecuta las pruebas
